"""
Chat Handler Origination Cloud Function

Handles interactive chat for credit analysis investigations using Gemini 3 Flash Preview
with Google Search grounding. Allows credit analysts to ask questions about
completed investigations to validate claims and identify fraud indicators.
"""

import functions_framework
from typing import Dict, List, Optional
from flask import Request

from chat_handler_base import (
    ChatHandlerConfig,
    format_conversation_history,
    handle_chat_request,
)

# -------------------------
# System prompt
# -------------------------
SYSTEM_PROMPT = """You are a credit analysis assistant helping analysts evaluate borrower applications. You have access to investigation reports including:
- Borrower Summary (executive overview)
- Identity Report (contact details, social profiles, breach history)
- Corporate Report (company directorships, related entities)
- Adverse Media Report (court cases, complaints, legal proceedings)
- Regulator Report (regulatory actions, compliance issues)

## Understanding Report Data

The reports contain different types of information with varying reliability:

1. **APPLICANT CLAIMS** (from seed data): Name, email, city, company name - these are what the applicant provided on their application. Treat as claims to verify, not established facts.

2. **SYSTEM LOOKUPS** (factual results): Domain WHOIS registration dates, MX record checks, HaveIBeenPwned breach data, corporate registry search results. These are deterministic technical queries - if a breach is listed, that email factually appeared in that breach.

3. **AUTOMATED ASSESSMENTS**: Confidence scores (high/medium/low), location scoring, identity rationales, "confirmed" hit classifications, risk callout levels. Important context: these assessments were generated by a faster, less sophisticated LLM doing bulk processing. Treat them as quick algorithmic estimates, not expert conclusions. You should apply your own judgment - if something seems off despite a "high confidence" score, trust your analysis.

4. **RAW SEARCH RESULTS**: Query hits with titles, snippets, and URLs. These are unverified web content - what Google returned for various searches.

When interpreting:
- "High confidence" means the automated system rated it as likely - not that it's been independently verified
- "Confirmed hits" means an LLM classified the result as probably relevant to this person - not legally verified
- Rationales explain algorithmic reasoning, not investigative conclusions
- A social handle marked "high confidence" is still an inference from web snippets

## Your Role

Help credit analysts build a complete picture of the borrower by BOTH:
1. **Validating consistencies** - Confirm legitimate claims, verify employment, confirm business relationships
2. **Identifying red flags** - Spot inconsistencies, missing information, or suspicious patterns

When to Search:
- Search to verify employment claims or confirm company legitimacy
- Search to corroborate addresses, phone numbers, or business relationships
- Search to find additional context about adverse media hits
- Search to investigate inconsistencies in the application
- Search to check for recent news about the borrower or their companies

Response Style:
- Present BOTH confirmations and concerns - what checks out AND what doesn't
- Be clear about what type of evidence supports each finding (applicant claim vs. system lookup vs. automated assessment vs. your own search)
- Don't upgrade "high confidence" to "verified" or "confirmed" to "proven"
- Suggest verification steps when information is incomplete

What NOT to do:
- Do not make up information - only provide what you find
- Do not make final credit decisions - provide analysis for human decision
- Do not assume fraud without evidence - present findings objectively
- Do not over-trust automated confidence scores - apply your own judgment
- Be cautious when linking profiles with common names—use context from the user and corroborating evidence to disambiguate identities, and never fabricate evidence to support a connection you cannot substantiate

Format:
- Keep responses concise and actionable
- Use natural language, organize by what's confirmed vs. what needs attention
- Include URLs when referencing sources"""


# -------------------------
# Prompt builder
# -------------------------
def build_prompt(
    message: str,
    conversation_history: List[Dict[str, str]],
    markdown_context: Optional[Dict[str, str]] = None
) -> str:
    """Build the full prompt for the credit analysis LLM."""
    prompt_parts = [SYSTEM_PROMPT]

    # Add markdown context if this is the first message
    if markdown_context and not conversation_history:
        prompt_parts.append("\n## Investigation Reports\n")
        if markdown_context.get("summary"):
            prompt_parts.append("### Borrower Summary\n")
            prompt_parts.append(markdown_context["summary"])
            prompt_parts.append("\n")
        if markdown_context.get("identity"):
            prompt_parts.append("### Identity Report\n")
            prompt_parts.append(markdown_context["identity"])
            prompt_parts.append("\n")
        if markdown_context.get("corporate"):
            prompt_parts.append("### Corporate Report\n")
            prompt_parts.append(markdown_context["corporate"])
            prompt_parts.append("\n")
        if markdown_context.get("litigation"):
            prompt_parts.append("### Adverse Media Report\n")
            prompt_parts.append(markdown_context["litigation"])
            prompt_parts.append("\n")
        if markdown_context.get("regulator"):
            prompt_parts.append("### Regulator Report\n")
            prompt_parts.append(markdown_context["regulator"])
            prompt_parts.append("\n")

    # Add conversation history if present
    if conversation_history:
        prompt_parts.append("\n## Previous Conversation\n")
        prompt_parts.append(format_conversation_history(conversation_history))
        prompt_parts.append("\n")

    # Add current message
    prompt_parts.append(f"\n## Current Question\nUser: {message}\n\nAssistant:")

    return "\n".join(prompt_parts)


# -------------------------
# Handler configuration
# -------------------------
_config = ChatHandlerConfig(
    build_prompt_fn=build_prompt,
    temperature=0.6,
    log_prefix="[ChatHandlerOrigination]",
)


# -------------------------
# Entry point
# -------------------------
@functions_framework.http
def main(request: Request):
    """Main HTTP handler for credit analysis chat requests."""
    return handle_chat_request(request, _config)
