"""
Chat Handler Origination Cloud Function

Handles interactive chat for credit analysis investigations using Gemini 3 Flash Preview
with Google Search grounding. Allows credit analysts to ask questions about
completed investigations to validate claims and identify fraud indicators.
"""

import functions_framework
import os
import json
from typing import Dict, Any, List, Optional
from flask import Request, jsonify

# Google Gen AI SDK imports (official SDK for Gemini 3 with grounding support)
from google import genai
from google.genai.types import GenerateContentConfig, Tool, GoogleSearch

# -------------------------
# Config
# -------------------------
GCP_PROJECT = os.environ.get("GCP_PROJECT", os.environ.get("GOOGLE_CLOUD_PROJECT", ""))
# Use 'global' endpoint for Gemini models - routes to any supported region
GCP_LOCATION = os.environ.get("GCP_LOCATION", "global")

# System prompt for credit analysis assistant
SYSTEM_PROMPT = """You are a credit analysis assistant helping analysts evaluate borrower applications. You have access to investigation reports including:
- Borrower Summary (executive overview)
- Identity Report (contact details, social profiles, breach history)
- Corporate Report (company directorships, related entities)
- Adverse Media Report (court cases, complaints, legal proceedings)
- Regulator Report (regulatory actions, compliance issues)

## Understanding Report Data

The reports contain different types of information with varying reliability:

1. **APPLICANT CLAIMS** (from seed data): Name, email, city, company name - these are what the applicant provided on their application. Treat as claims to verify, not established facts.

2. **SYSTEM LOOKUPS** (factual results): Domain WHOIS registration dates, MX record checks, HaveIBeenPwned breach data, corporate registry search results. These are deterministic technical queries - if a breach is listed, that email factually appeared in that breach.

3. **AUTOMATED ASSESSMENTS**: Confidence scores (high/medium/low), location scoring, identity rationales, "confirmed" hit classifications, risk callout levels. Important context: these assessments were generated by a faster, less sophisticated LLM doing bulk processing. Treat them as quick algorithmic estimates, not expert conclusions. You should apply your own judgment - if something seems off despite a "high confidence" score, trust your analysis.

4. **RAW SEARCH RESULTS**: Query hits with titles, snippets, and URLs. These are unverified web content - what Google returned for various searches.

When interpreting:
- "High confidence" means the automated system rated it as likely - not that it's been independently verified
- "Confirmed hits" means an LLM classified the result as probably relevant to this person - not legally verified
- Rationales explain algorithmic reasoning, not investigative conclusions
- A social handle marked "high confidence" is still an inference from web snippets

## Your Role

Help credit analysts build a complete picture of the borrower by BOTH:
1. **Validating consistencies** - Confirm legitimate claims, verify employment, confirm business relationships
2. **Identifying red flags** - Spot inconsistencies, missing information, or suspicious patterns

When to Search:
- Search to verify employment claims or confirm company legitimacy
- Search to corroborate addresses, phone numbers, or business relationships
- Search to find additional context about adverse media hits
- Search to investigate inconsistencies in the application
- Search to check for recent news about the borrower or their companies

Response Style:
- Present BOTH confirmations and concerns - what checks out AND what doesn't
- Be clear about what type of evidence supports each finding (applicant claim vs. system lookup vs. automated assessment vs. your own search)
- Don't upgrade "high confidence" to "verified" or "confirmed" to "proven"
- Suggest verification steps when information is incomplete

What NOT to do:
- Do not make up information - only provide what you find
- Do not make final credit decisions - provide analysis for human decision
- Do not assume fraud without evidence - present findings objectively
- Do not over-trust automated confidence scores - apply your own judgment
- Be cautious when linking profiles with common names—use context from the user and corroborating evidence to disambiguate identities, and never fabricate evidence to support a connection you cannot substantiate

Format:
- Keep responses concise and actionable
- Use natural language, organize by what's confirmed vs. what needs attention
- Include URLs when referencing sources"""


def format_conversation_history(history: List[Dict[str, str]]) -> str:
    """Format conversation history for the prompt."""
    if not history:
        return ""
    
    formatted = []
    for msg in history:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        if role == "user":
            formatted.append(f"User: {content}")
        elif role == "assistant":
            formatted.append(f"Assistant: {content}")
    
    return "\n".join(formatted)


def build_prompt(
    message: str,
    conversation_history: List[Dict[str, str]],
    markdown_context: Optional[Dict[str, str]] = None
) -> str:
    """Build the full prompt for the LLM."""
    prompt_parts = [SYSTEM_PROMPT]
    
    # Add markdown context if this is the first message
    if markdown_context and not conversation_history:
        prompt_parts.append("\n## Investigation Reports\n")
        if markdown_context.get("summary"):
            prompt_parts.append("### Borrower Summary\n")
            prompt_parts.append(markdown_context["summary"])
            prompt_parts.append("\n")
        if markdown_context.get("identity"):
            prompt_parts.append("### Identity Report\n")
            prompt_parts.append(markdown_context["identity"])
            prompt_parts.append("\n")
        if markdown_context.get("corporate"):
            prompt_parts.append("### Corporate Report\n")
            prompt_parts.append(markdown_context["corporate"])
            prompt_parts.append("\n")
        if markdown_context.get("litigation"):
            prompt_parts.append("### Adverse Media Report\n")
            prompt_parts.append(markdown_context["litigation"])
            prompt_parts.append("\n")
        if markdown_context.get("regulator"):
            prompt_parts.append("### Regulator Report\n")
            prompt_parts.append(markdown_context["regulator"])
            prompt_parts.append("\n")
    
    # Add conversation history if present
    if conversation_history:
        prompt_parts.append("\n## Previous Conversation\n")
        prompt_parts.append(format_conversation_history(conversation_history))
        prompt_parts.append("\n")
    
    # Add current message
    prompt_parts.append(f"\n## Current Question\nUser: {message}\n\nAssistant:")
    
    return "\n".join(prompt_parts)


def extract_grounding_metadata(response) -> Dict[str, Any]:
    """Extract grounding metadata from Google Gen AI SDK response."""
    metadata = {
        "search_entry_point": "",
        "web_search_queries": [],
        "grounding_chunks": []
    }
    
    try:
        # Google Gen AI SDK response structure
        if hasattr(response, 'candidates') and response.candidates:
            candidate = response.candidates[0]
            
            # Extract grounding metadata if available
            if hasattr(candidate, 'grounding_metadata'):
                grounding = candidate.grounding_metadata
                
                # Extract search queries
                if hasattr(grounding, 'web_search_queries'):
                    metadata["web_search_queries"] = list(grounding.web_search_queries)
                
                # Extract grounding chunks
                if hasattr(grounding, 'grounding_chunks'):
                    chunks = []
                    for chunk in grounding.grounding_chunks:
                        chunk_data = {}
                        if hasattr(chunk, 'web'):
                            chunk_data["web"] = {
                                "uri": getattr(chunk.web, 'uri', ''),
                                "title": getattr(chunk.web, 'title', '')
                            }
                        chunks.append(chunk_data)
                    metadata["grounding_chunks"] = chunks
                
                # Extract search entry point (HTML/CSS for display)
                if hasattr(grounding, 'search_entry_point'):
                    entry_point = grounding.search_entry_point
                    if hasattr(entry_point, 'rendered_content'):
                        metadata["search_entry_point"] = entry_point.rendered_content
                    elif hasattr(entry_point, 'html'):
                        metadata["search_entry_point"] = entry_point.html
        
        # Log usage metadata for debugging
        if hasattr(response, 'usage_metadata'):
            print(f"[ChatHandlerOrigination] Usage metadata: {response.usage_metadata}")
    
    except Exception as e:
        print(f"[ChatHandlerOrigination] Warning: Could not extract grounding metadata: {e}")
        import traceback
        traceback.print_exc()
    
    return metadata


@functions_framework.http
def main(request: Request):
    """Main HTTP handler for chat requests."""
    # Enable CORS
    if request.method == "OPTIONS":
        headers = {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
            "Access-Control-Allow-Headers": "Content-Type",
            "Access-Control-Max-Age": "3600",
        }
        return ("", 204, headers)
    
    headers = {"Access-Control-Allow-Origin": "*"}
    
    if request.method != "POST":
        return jsonify({"error": "Method not allowed"}), 405, headers
    
    try:
        data = request.get_json() or {}
    except Exception:
        return jsonify({"error": "Invalid JSON"}), 400, headers
    
    # Extract request data
    message = (data.get("message") or "").strip()
    conversation_history = data.get("conversation_history", [])
    markdown_context = data.get("markdown_context")
    
    # Validate required fields
    if not message:
        return jsonify({"error": "message is required"}), 400, headers
    
    if not isinstance(conversation_history, list):
        return jsonify({"error": "conversation_history must be a list"}), 400, headers
    
    # Validate conversation history format
    for msg in conversation_history:
        if not isinstance(msg, dict) or "role" not in msg or "content" not in msg:
            return jsonify({"error": "Invalid conversation_history format"}), 400, headers
    
    # Initialize Google Gen AI client with Vertex AI
    if not GCP_PROJECT:
        return jsonify({"error": "GCP_PROJECT not configured"}), 500, headers
    
    try:
        # Initialize client with Vertex AI (official SDK pattern)
        client = genai.Client(
            vertexai=True,
            project=GCP_PROJECT,
            location=GCP_LOCATION
        )
        print(f"[ChatHandlerOrigination] Initialized Google Gen AI client for Vertex AI")
    except Exception as e:
        print(f"[ChatHandlerOrigination] Google Gen AI client initialization error: {e}")
        import traceback
        traceback.print_exc()
        return jsonify({"error": f"Client initialization failed: {str(e)}"}), 500, headers
    
    # Build prompt
    try:
        prompt = build_prompt(message, conversation_history, markdown_context)
    except Exception as e:
        print(f"[ChatHandlerOrigination] Error building prompt: {e}")
        return jsonify({"error": f"Failed to build prompt: {str(e)}"}), 500, headers
    
    # Call Gemini 3 Flash Preview with Google Search grounding
    try:
        # Configure Google Search grounding tool (official SDK pattern)
        google_search_tool = Tool(google_search=GoogleSearch())
        
        # Create config with grounding tool
        # Conservative settings for credit analysis accuracy
        config = GenerateContentConfig(
            tools=[google_search_tool],
            temperature=0.6,  # Moderate temperature - grounded but not overly literal
            max_output_tokens=2048,  # Ensure complete responses
            top_p=0.9,  # Slightly constrain sampling for consistency
        )
        
        print(f"[ChatHandlerOrigination] Calling Gemini 3 Flash Preview with Google Search grounding...")
        
        # Generate response using official SDK pattern
        response = client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=prompt,
            config=config
        )
        
        if not response or not hasattr(response, 'text') or not response.text:
            return jsonify({
                "error": "Empty response from LLM",
                "response": "I apologize, but I couldn't generate a response. Please try again."
            }), 500, headers
        
        # Extract response text
        response_text = response.text.strip()
        
        # Extract grounding metadata
        grounding_metadata = extract_grounding_metadata(response)
        
        print(f"[ChatHandlerOrigination] Response generated successfully ({len(response_text)} chars)")
        
        # Build updated conversation history
        updated_history = conversation_history.copy()
        updated_history.append({"role": "user", "content": message})
        updated_history.append({"role": "assistant", "content": response_text})
        
        # Return response
        return jsonify({
            "response": response_text,
            "conversation_history": updated_history,
            "grounding_metadata": grounding_metadata
        }), 200, headers
    
    except Exception as e:
        print(f"[ChatHandlerOrigination] Error calling Gemini: {e}")
        import traceback
        traceback.print_exc()
        
        # Return error in response field (as per design)
        return jsonify({
            "error": f"Chat processing failed: {str(e)}",
            "response": f"I encountered an error while processing your request: {str(e)}. Please try again."
        }), 500, headers
