// ============================================================================
// Chrome Extension Configuration
// ============================================================================
// Generated by Terraform. DO NOT edit manually.
// This file is generated during deployment with project-specific values.
// ============================================================================

const CONFIG = {
  // Skip Trace Intelligence Platform URL
  SKIP_TRACE_INTELLIGENCE_URL: 'https://YOUR_PROJECT_ID-skiptrace.web.app/index.html',
  
  // Version info for debugging
  VERSION: '1.0.0',
  ENVIRONMENT: 'production',
  PROJECT_ID: 'YOUR_PROJECT_ID'
};

// Export for use in background.js
if (typeof window !== 'undefined') {
  window.CONFIG = CONFIG;
}
