// ============================================================================
// Chrome Extension Configuration
// ============================================================================
// Generated by Terraform. DO NOT edit manually.
// Generated at: 2026-02-02T20:04:25Z
// Project: mikiri-demo-test
// ============================================================================

const CONFIG = {
  // Skip Trace Intelligence Platform URL
  SKIP_TRACE_INTELLIGENCE_URL: 'https://mikiri-demo-test-skiptrace.web.app/index.html',
  
  // Version info for debugging
  VERSION: '1.0.0',
  ENVIRONMENT: 'production',
  PROJECT_ID: 'mikiri-demo-test'
};

// Export for use in background.js
if (typeof window !== 'undefined') {
  window.CONFIG = CONFIG;
}
